# .goreleaser.yml - Anheyu App Release Configuration

# GoReleaser 配置版本
version: 2

# 项目配置
project_name: anheyu-app

# 环境变量
env:
  - GO111MODULE=on
  - CGO_ENABLED=0

# 构建前钩子 - 构建前端资源
before:
  hooks:
    - go mod tidy
    - go mod download

# 构建配置
builds:
  - id: anheyu-app
    main: ./main.go
    binary: anheyu-app

    # 版本信息注入
    ldflags:
      - -s -w
      - -X 'github.com/anzhiyu-c/anheyu-app/internal/pkg/version.Version={{.Version}}'
      - -X 'github.com/anzhiyu-c/anheyu-app/internal/pkg/version.Commit={{.ShortCommit}}'
      - -X 'github.com/anzhiyu-c/anheyu-app/internal/pkg/version.Date={{.Date}}'

    # 构建目标
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    # 特定平台配置
    goamd64:
      - v1

    # 忽略特定组合
    ignore:
      - goos: windows
        goarch: arm64

    # 输出文件名模板
    hooks:
      post:
        - cmd: echo "Built {{ .Path }}"

# 归档配置
archives:
  - id: anheyu-app-archives
    # GoReleaser v2 自动关联所有构建，无需指定 builds

    # 归档文件名模板
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    # 文件格式 (v2 最新语法)
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

    # 包含的文件 (现在可以使用简单glob，因为有.gitkeep文件)
    files:
      - README.md
      - LICENSE
      - entrypoint.sh
      - default_files/**/*

# Checksum 配置
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# 快照配置
snapshot:
  # GoReleaser v2 使用 version_template 替代 name_template
  version_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

# 更新日志配置
changelog:
  sort: asc
  use: github

  filters:
    exclude:
      - "^docs\\([\\w]+\\):"
      - "^test\\([\\w]+\\):"
      - "^ci\\([\\w]+\\):"
      - "^build\\([\\w]+\\):"
      - "^style\\([\\w]+\\):"
      - "^refactor\\([\\w]+\\):"
      - "Merge pull request"
      - "Merge branch"

  groups:
    - title: "🚀 Features"
      regexp: "^feat\\([\\w]+\\): .*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^fix\\([\\w]+\\): .*$"
      order: 1
    - title: "📚 Documentation"
      regexp: "^docs\\([\\w]+\\): .*$"
      order: 2
    - title: "⚡ Performance"
      regexp: "^perf\\([\\w]+\\): .*$"
      order: 3
    - title: "🔧 Maintenance"
      regexp: "^(chore|refactor|style)\\([\\w]+\\): .*$"
      order: 999

# Docker 镜像配置 - 使用修复后的 dockers 格式
dockers:
  - id: anheyu-app-docker
    goos: linux
    goarch: amd64

    image_templates:
      - 'anheyu/anheyu-backend:{{ if eq (substr .Tag 0 1) "v" }}{{ substr .Tag 1 }}{{ else }}{{ .Tag }}{{ end }}'
      - "anheyu/anheyu-backend:latest"

    dockerfile: Dockerfile
    use: buildx

    build_flag_templates:
      - "--platform=linux/amd64"
      - "--pull"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=COMMIT={{ .ShortCommit }}"
      - "--build-arg=BUILD_DATE={{ .Date }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"

    extra_files:
      - README.md
      - LICENSE
      - entrypoint.sh
      - default_files/

# GitHub Release 配置
release:
  github:
    owner: anzhiyu-c
    name: anheyu-app

  # Release 名称
  name_template: "Anheyu App {{ .Tag }}"

  # 发布模式
  mode: replace

  # 预发布检测
  prerelease: auto

  # Release Notes 模板
  header: |
    ## Anheyu App {{ .Tag }}

    🎉 **新版本发布！**

    ### 📋 构建信息
    - **版本**: `{{ .Tag }}`
    - **Commit**: [`{{ .ShortCommit }}`](https://github.com/anzhiyu-c/anheyu-app/commit/{{ .FullCommit }})
    - **构建时间**: `{{ .Date }}`
    - **Go 版本**: `{{ .Env.GOVERSION }}`

    ### 📦 下载

    通过 [GitHub Releases](https://github.com/anzhiyu-c/anheyu-app/releases/tag/{{ .Tag }}) 下载适合您系统的版本：

    - **Linux AMD64**: `anheyu-app_{{ .Tag }}_linux_amd64.tar.gz`
    - **Linux ARM64**: `anheyu-app_{{ .Tag }}_linux_arm64.tar.gz`  
    - **macOS AMD64**: `anheyu-app_{{ .Tag }}_darwin_amd64.tar.gz`
    - **macOS ARM64**: `anheyu-app_{{ .Tag }}_darwin_arm64.tar.gz`
    - **Windows AMD64**: `anheyu-app_{{ .Tag }}_windows_amd64.zip`

    ### 🐳 Docker 镜像
    ```bash
    # 拉取最新版本
    docker pull anheyu/anheyu-backend:{{ if eq (substr .Tag 0 1) "v" }}{{ substr .Tag 1 }}{{ else }}{{ .Tag }}{{ end }}
    docker pull anheyu/anheyu-backend:latest

    # 多架构支持自动选择
    ```

    ### 🚀 快速开始
    ```bash
    # 下载并运行
    wget https://github.com/anzhiyu-c/anheyu-app/releases/download/{{ .Tag }}/anheyu-app_{{ .Tag }}_linux_amd64.tar.gz
    tar -xzf anheyu-app_{{ .Tag }}_linux_amd64.tar.gz
    ./anheyu-app

    # 或使用 Docker
    docker run -d -p 8091:8091 anheyu/anheyu-backend:{{ if eq (substr .Tag 0 1) "v" }}{{ substr .Tag 1 }}{{ else }}{{ .Tag }}{{ end }}
    ```

  footer: |
    ---

    ### 📚 相关链接
    - [完整更新日志](https://github.com/anzhiyu-c/anheyu-app/releases)
    - [文档](https://github.com/anzhiyu-c/anheyu-app/blob/main/README.md)
    - [问题反馈](https://github.com/anzhiyu-c/anheyu-app/issues)

    **完整的 SHA256 校验和**：[anheyu-app_{{ .Tag }}_checksums.txt](https://github.com/anzhiyu-c/anheyu-app/releases/download/{{ .Tag }}/anheyu-app_{{ .Tag }}_checksums.txt)

# 公告配置
announce:
  skip: "{{gt .Patch 0}}" # 跳过 patch 版本的公告
