services:
  anheyu:
    build: .
    container_name: anheyu-backend
    depends_on:
      - postgresql
      - redis
    restart: always
    ports:
      - 8091:8091
    environment:
      - ANHEYU_DATABASE_TYPE=postgres
      - ANHEYU_DATABASE_HOST=postgresql
      - ANHEYU_DATABASE_USER=anheyu
      - ANHEYU_DATABASE_NAME=anheyu
      - ANHEYU_DATABASE_PORT=5432
      - ANHEYU_DATABASE_PASSWORD=
      - ANHEYU_REDIS_ADDR=redis:6379
    volumes:
      - ./data:/anheyu/data

  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=anheyu
      - POSTGRES_DB=anheyu
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - database_postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data

volumes:
  database_postgres:
  redis_data:
