# .github/workflows/build.yml

name: Build, Release and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          token: ${{ secrets.GH_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download Go modules
        run: go mod download

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: assets/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('assets/pnpm-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install pnpm
        run: npm install -g pnpm@9

      - name: Install Frontend
        run: |
          cd assets
          pnpm install

      - name: Build Frontend
        run: |
          cd assets
          pnpm run build

      - name: Cross-compile for Linux amd64
        run: GOOS=linux GOARCH=amd64 GOAMD64=v1 go build -trimpath -ldflags="-s -w" -o anheyu-app-linux-amd64 .

      - name: Cross-compile for Linux arm64
        run: GOOS=linux GOARCH=arm64 go build -trimpath -ldflags="-s -w" -o anheyu-app-linux-arm64 .

      - name: Cross-compile for Windows amd64
        run: GOOS=windows GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o anheyu-app-windows-amd64.exe .

      - name: Cross-compile for macOS amd64
        run: GOOS=darwin GOARCH=amd64 go build -trimpath -ldflags="-s -w" -o anheyu-app-macos-amd64 .

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            anheyu-app-linux-amd64
            anheyu-app-linux-arm64
            anheyu-app-windows-amd64.exe
            anheyu-app-macos-amd64
            data/

  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: .
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCK-USERNAME }}
          password: ${{ secrets.DOCK-TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: anheyu/anheyu-backend
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: .
      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            anheyu-app-linux-amd64
            anheyu-app-linux-arm64
            anheyu-app-windows-amd64.exe
            anheyu-app-macos-amd64
